version: '3'

services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
      - "5858:5858"
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
  db:
    image: mongo
#     expose:
#       - "27017"
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
